/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.lk.ui;

import edu.ijse.lk.controller.BranchController;
import edu.ijse.lk.controller.CategoryController;
import edu.ijse.lk.controller.CustomerController;
import edu.ijse.lk.controller.EquipmentController;
import edu.ijse.lk.controller.MembershipController;
import edu.ijse.lk.controller.RentalController;
import edu.ijse.lk.controller.ReportController;
import edu.ijse.lk.controller.ReservationController;
import edu.ijse.lk.dto.BranchDTO;
import edu.ijse.lk.dto.CategoryDTO;
import edu.ijse.lk.dto.CustomerDTO;
import edu.ijse.lk.dto.EquipmentDTO;
import edu.ijse.lk.dto.MembershipDTO;
import edu.ijse.lk.dto.RentalDTO;
import edu.ijse.lk.dto.ReservationDTO;
import edu.ijse.lk.dto.RevenueReportDTO;
import edu.ijse.lk.dto.UserDTO;
import edu.ijse.lk.dto.UtilizationReportDTO;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pulindu
 */
public class MainUi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainUi.class.getName());
    private final UserDTO user;
    private final BranchController branchController = new BranchController();
    private final CategoryController categoryController = new CategoryController();
    private final EquipmentController equipmentController = new EquipmentController();
    private final CustomerController customerController = new CustomerController();
    private final MembershipController membershipController = new MembershipController();
    private final ReservationController reservationController = new ReservationController();
    private final RentalController rentalController = new RentalController();
    private final ReportController reportController = new ReportController();

    /**
     * Creates new form MainUi
     */
    
    
    public MainUi() {
        this(null);
    }

    public MainUi(UserDTO user) {
        this.user = user;
        initComponents();
        setLocationRelativeTo(null);

        if (user != null) {
            setTitle("GearRent Pro - " + user.username + " (" + user.role + ")");
        }

        configureRoleAccess();
        initializeData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        branchBtnAdd3 = new javax.swing.JButton();
        branchBtnUpdate3 = new javax.swing.JButton();
        branchBtnDlt3 = new javax.swing.JButton();
        branchBtnRefresh3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        ctgBtnAdd = new javax.swing.JButton();
        ctgBtnUpdate = new javax.swing.JButton();
        ctgBtnActive = new javax.swing.JButton();
        ctgBtnRefresh = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        eqpBtnSearch = new javax.swing.JButton();
        eqpBtnAdd = new javax.swing.JButton();
        eqpBtnUpdate = new javax.swing.JButton();
        eqpBtnRefresh = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        ctmBtnAdd = new javax.swing.JButton();
        ctmBtnUpdate = new javax.swing.JButton();
        ctmBtnRefresh = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        mbshipBtnRefresh = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        revervBtnCreate = new javax.swing.JButton();
        revervBtnConvertToRental = new javax.swing.JButton();
        revervBtnCancel = new javax.swing.JButton();
        revervBtnRefresh = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        rentalBtnCreate = new javax.swing.JButton();
        rentalBtnReturn = new javax.swing.JButton();
        rentalBtnOverdue = new javax.swing.JButton();
        rentalBtnRefresh = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable12 = new javax.swing.JTable();
        reportBtnRevenue = new javax.swing.JButton();
        reportBtnEqpUtil = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane4.setBackground(new java.awt.Color(229, 229, 229));
        jTabbedPane4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Branch ID", "Branch Code", "Name", "Contact"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        branchBtnAdd3.setText("Add");
        branchBtnAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchBtnAddActionPerformed(evt);
            }
        });

        branchBtnUpdate3.setText("Update");
        branchBtnUpdate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchBtnUpdateActionPerformed(evt);
            }
        });

        branchBtnDlt3.setText("Delete");
        branchBtnDlt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchBtnDltActionPerformed(evt);
            }
        });

        branchBtnRefresh3.setText("Refresh");
        branchBtnRefresh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchBtnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(branchBtnRefresh3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(branchBtnAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(branchBtnUpdate3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(branchBtnDlt3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(branchBtnAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branchBtnUpdate3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branchBtnDlt3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branchBtnRefresh3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Branches", jPanel5);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price Factor", "Weekend Multiplier", "Late Fee/Day", "Active Status"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        ctgBtnAdd.setText("Add");
        ctgBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctgBtnAddActionPerformed(evt);
            }
        });

        ctgBtnUpdate.setText("Update");
        ctgBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctgBtnUpdateActionPerformed(evt);
            }
        });

        ctgBtnActive.setText("Set Active");
        ctgBtnActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctgBtnActiveActionPerformed(evt);
            }
        });

        ctgBtnRefresh.setText("Refresh");
        ctgBtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctgBtnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ctgBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctgBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctgBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctgBtnActive, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
            .addComponent(jScrollPane6)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctgBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctgBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctgBtnActive, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctgBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Categories", jPanel6);

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Branch ID", "Category ID", "Brand", "Model", "Current Status"
            }
        ));
        jScrollPane7.setViewportView(jTable7);

        eqpBtnSearch.setText("Search");
        eqpBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eqpBtnSearchActionPerformed(evt);
            }
        });

        eqpBtnAdd.setText("Add");
        eqpBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eqpBtnAddActionPerformed(evt);
            }
        });

        eqpBtnUpdate.setText("Update");
        eqpBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eqpBtnUpdateActionPerformed(evt);
            }
        });

        eqpBtnRefresh.setText("Refresh");
        eqpBtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eqpBtnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(eqpBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eqpBtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eqpBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eqpBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eqpBtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eqpBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eqpBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eqpBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Equipment", jPanel7);

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer ID", "Name", "NIC/Passport", "Membership ID"
            }
        ));
        jScrollPane8.setViewportView(jTable8);

        ctmBtnAdd.setText("Add");
        ctmBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctmBtnAddActionPerformed(evt);
            }
        });

        ctmBtnUpdate.setText("Update");
        ctmBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctmBtnUpdateActionPerformed(evt);
            }
        });

        ctmBtnRefresh.setText("Refresh");
        ctmBtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctmBtnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ctmBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctmBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctmBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctmBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctmBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctmBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Customers", jPanel8);

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Membership ID", "Level Name", "Discount Percentage"
            }
        ));
        jScrollPane9.setViewportView(jTable9);

        mbshipBtnRefresh.setText("Refresh");
        mbshipBtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbshipBtnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mbshipBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mbshipBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Memberships", jPanel9);

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Reservation ID", "Equipment ID", "Customer ID", "Start Date", "End Date", "Status"
            }
        ));
        jScrollPane10.setViewportView(jTable10);

        revervBtnCreate.setText("Create");
        revervBtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revervBtnCreateActionPerformed(evt);
            }
        });

        revervBtnConvertToRental.setText("Convert to Rental");
        revervBtnConvertToRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revervBtnConvertToRentalActionPerformed(evt);
            }
        });

        revervBtnCancel.setText("Cancel");
        revervBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revervBtnCancelActionPerformed(evt);
            }
        });

        revervBtnRefresh.setText("Refresh");
        revervBtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revervBtnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(revervBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(revervBtnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(revervBtnConvertToRental, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(revervBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(revervBtnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(revervBtnConvertToRental, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(revervBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(revervBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Reservations", jPanel10);

        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Rental ID", "Equipment ID", "Customer ID", "Rental Period", "Final Amount", "Late Fee", "Damage Charge", "Settlement Amount", "Status"
            }
        ));
        jScrollPane11.setViewportView(jTable11);

        rentalBtnCreate.setText("Create");
        rentalBtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalBtnCreateActionPerformed(evt);
            }
        });

        rentalBtnReturn.setText("Return");
        rentalBtnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalBtnReturnActionPerformed(evt);
            }
        });

        rentalBtnOverdue.setText("Overdue");
        rentalBtnOverdue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalBtnOverdueActionPerformed(evt);
            }
        });

        rentalBtnRefresh.setText("Refresh");
        rentalBtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalBtnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane11)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(rentalBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rentalBtnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rentalBtnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rentalBtnOverdue, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentalBtnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentalBtnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentalBtnOverdue, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentalBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Rentals", jPanel11);

        jTable12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane12.setViewportView(jTable12);

        reportBtnRevenue.setText("Branch Revenue");
        reportBtnRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportBtnRevenueActionPerformed(evt);
            }
        });

        reportBtnEqpUtil.setText("Equipment Utilization");
        reportBtnEqpUtil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportBtnEqpUtilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(reportBtnRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportBtnEqpUtil, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportBtnRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportBtnEqpUtil, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Reports", jPanel12);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GearRent Pro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(884, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 579, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reportBtnEqpUtilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBtnEqpUtilActionPerformed
        runAction(() -> {
            LocalDate from = dateInput("From Date (YYYY-MM-DD)");
            LocalDate to = dateInput("To Date (YYYY-MM-DD)");
            DefaultTableModel model = new DefaultTableModel(
                new Object[]{"Equipment ID", "Equipment", "Rental Days", "Available Days"},
                0
            );
            for (UtilizationReportDTO row : reportController.utilization(from, to)) {
                model.addRow(new Object[]{row.equipmentId, row.equipmentName, row.rentalDays, row.availableDays});
            }
            jTable12.setModel(model);
        }, null);
    }//GEN-LAST:event_reportBtnEqpUtilActionPerformed

    private void reportBtnRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBtnRevenueActionPerformed
        runAction(() -> {
            LocalDate from = dateInput("From Date (YYYY-MM-DD)");
            LocalDate to = dateInput("To Date (YYYY-MM-DD)");
            DefaultTableModel model = new DefaultTableModel(new Object[]{"Branch ID", "Branch Name", "Revenue"}, 0);
            for (RevenueReportDTO row : reportController.revenue(from, to)) {
                model.addRow(new Object[]{row.branchId, row.branchName, row.revenue});
            }
            jTable12.setModel(model);
        }, null);
    }//GEN-LAST:event_reportBtnRevenueActionPerformed

    private void rentalBtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalBtnRefreshActionPerformed
        loadRentals();
    }//GEN-LAST:event_rentalBtnRefreshActionPerformed

    private void rentalBtnOverdueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalBtnOverdueActionPerformed
        loadRentals(rentalController.overdue(scopeBranch()));
    }//GEN-LAST:event_rentalBtnOverdueActionPerformed

    private void rentalBtnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalBtnReturnActionPerformed
        runAction(() -> rentalController.returnRental(
            intInput("Rental ID"),
            dateInput("Actual Return Date (YYYY-MM-DD)"),
            decimalInput("Damage Charge")
        ), this::loadRentals);
    }//GEN-LAST:event_rentalBtnReturnActionPerformed

    private void rentalBtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalBtnCreateActionPerformed
        runAction(() -> {
            RentalDTO dto = new RentalDTO();
            dto.equipmentId = intInput("Equipment ID");
            dto.customerId = intInput("Customer ID");
            dto.branchId = inputBranch();
            dto.startDate = dateInput("Start Date (YYYY-MM-DD)");
            dto.endDate = dateInput("End Date (YYYY-MM-DD)");
            rentalController.create(dto);
        }, this::loadRentals);
    }//GEN-LAST:event_rentalBtnCreateActionPerformed

    private void revervBtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revervBtnRefreshActionPerformed
        loadReservations();
    }//GEN-LAST:event_revervBtnRefreshActionPerformed

    private void revervBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revervBtnCancelActionPerformed
        runAction(() -> reservationController.cancel(intInput("Reservation ID")), this::loadReservations);
    }//GEN-LAST:event_revervBtnCancelActionPerformed

    private void revervBtnConvertToRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revervBtnConvertToRentalActionPerformed
        runAction(() -> reservationController.convertToRental(intInput("Reservation ID")), this::loadReservations);
    }//GEN-LAST:event_revervBtnConvertToRentalActionPerformed

    private void revervBtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revervBtnCreateActionPerformed
        runAction(() -> {
            ReservationDTO dto = new ReservationDTO();
            dto.equipmentId = intInput("Equipment ID");
            dto.customerId = intInput("Customer ID");
            dto.branchId = inputBranch();
            dto.startDate = dateInput("Start Date (YYYY-MM-DD)");
            dto.endDate = dateInput("End Date (YYYY-MM-DD)");
            reservationController.create(dto);
        }, this::loadReservations);
    }//GEN-LAST:event_revervBtnCreateActionPerformed

    private void mbshipBtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbshipBtnRefreshActionPerformed
        loadMemberships();
    }//GEN-LAST:event_mbshipBtnRefreshActionPerformed

    private void ctmBtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctmBtnRefreshActionPerformed
        loadCustomers();
    }//GEN-LAST:event_ctmBtnRefreshActionPerformed

    private void ctmBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctmBtnUpdateActionPerformed
        runAction(() -> {
            CustomerDTO dto = new CustomerDTO();
            dto.customerId = intInput("Customer ID");
            dto.name = input("Name");
            dto.nicPassport = input("NIC/Passport");
            dto.contactNo = input("Phone");
            dto.email = input("Email");
            dto.address = input("Address");
            dto.membershipId = nullableIntInput("Membership ID (optional)");
            customerController.update(dto);
        }, this::loadCustomers);
    }//GEN-LAST:event_ctmBtnUpdateActionPerformed

    private void ctmBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctmBtnAddActionPerformed
        runAction(() -> {
            CustomerDTO dto = new CustomerDTO();
            dto.name = input("Name");
            dto.nicPassport = input("NIC/Passport");
            dto.contactNo = input("Phone");
            dto.email = input("Email");
            dto.address = input("Address");
            dto.membershipId = nullableIntInput("Membership ID (optional)");
            customerController.create(dto);
        }, this::loadCustomers);
    }//GEN-LAST:event_ctmBtnAddActionPerformed

    private void eqpBtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eqpBtnRefreshActionPerformed
        loadEquipment();
    }//GEN-LAST:event_eqpBtnRefreshActionPerformed

    private void eqpBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eqpBtnUpdateActionPerformed
        runAction(() -> {
            EquipmentDTO dto = new EquipmentDTO();
            dto.equipmentId = intInput("Equipment ID");
            dto.categoryId = intInput("Category ID");
            dto.branchId = inputBranch();
            dto.brand = input("Brand");
            dto.model = input("Model");
            dto.purchaseYear = intInput("Purchase Year");
            dto.baseDailyPrice = decimalInput("Base Daily Price");
            dto.securityDeposit = decimalInput("Security Deposit");
            dto.status = input("Status (Available/Reserved/Rented/Under Maintenance)");
            equipmentController.update(dto);
        }, this::loadEquipment);
    }//GEN-LAST:event_eqpBtnUpdateActionPerformed

    private void eqpBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eqpBtnAddActionPerformed
        runAction(() -> {
            EquipmentDTO dto = new EquipmentDTO();
            dto.categoryId = intInput("Category ID");
            dto.branchId = inputBranch();
            dto.brand = input("Brand");
            dto.model = input("Model");
            dto.purchaseYear = intInput("Purchase Year");
            dto.baseDailyPrice = decimalInput("Base Daily Price");
            dto.securityDeposit = decimalInput("Security Deposit");
            dto.status = "Available";
            equipmentController.create(dto);
        }, this::loadEquipment);
    }//GEN-LAST:event_eqpBtnAddActionPerformed

    private void eqpBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eqpBtnSearchActionPerformed
        runAction(() -> {
            Integer categoryId = nullableIntInput("Category ID (optional)");
            String brand = nullableInput("Brand (optional)");
            String model = nullableInput("Model (optional)");
            String status = nullableInput("Status (Available/Reserved/Rented/Under Maintenance)");
            loadEquipment(equipmentController.search(scopeBranch(), categoryId, brand, model, status));
        }, null);
    }//GEN-LAST:event_eqpBtnSearchActionPerformed

    private void ctgBtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctgBtnRefreshActionPerformed
        loadCategories();
    }//GEN-LAST:event_ctgBtnRefreshActionPerformed

    private void ctgBtnActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctgBtnActiveActionPerformed
        runAction(() -> categoryController.setActive(intInput("Category ID"), boolInput("Active (true/false)")), this::loadCategories);
    }//GEN-LAST:event_ctgBtnActiveActionPerformed

    private void ctgBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctgBtnUpdateActionPerformed
        runAction(() -> {
            CategoryDTO dto = new CategoryDTO();
            dto.categoryId = intInput("Category ID");
            dto.name = input("Name");
            dto.description = input("Description");
            dto.priceFactor = decimalInput("Price Factor");
            dto.weekendMultiplier = decimalInput("Weekend Multiplier");
            dto.lateFeePerDay = decimalInput("Late Fee Per Day");
            dto.active = boolInput("Active (true/false)");
            categoryController.update(dto);
        }, this::loadCategories);
    }//GEN-LAST:event_ctgBtnUpdateActionPerformed

    private void ctgBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctgBtnAddActionPerformed
        runAction(() -> {
            CategoryDTO dto = new CategoryDTO();
            dto.name = input("Name");
            dto.description = input("Description");
            dto.priceFactor = decimalInput("Price Factor");
            dto.weekendMultiplier = decimalInput("Weekend Multiplier");
            dto.lateFeePerDay = decimalInput("Late Fee Per Day");
            dto.active = true;
            categoryController.create(dto);
        }, this::loadCategories);
    }//GEN-LAST:event_ctgBtnAddActionPerformed

    private void branchBtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchBtnRefreshActionPerformed
        loadBranches();
    }//GEN-LAST:event_branchBtnRefreshActionPerformed

    private void branchBtnDltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchBtnDltActionPerformed
        runAction(() -> branchController.delete(intInput("Branch ID")), this::loadBranches);
    }//GEN-LAST:event_branchBtnDltActionPerformed

    private void branchBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchBtnUpdateActionPerformed
        runAction(() -> {
            BranchDTO dto = new BranchDTO();
            dto.branchId = intInput("Branch ID");
            dto.branchCode = input("Branch Code");
            dto.name = input("Name");
            dto.address = input("Address");
            dto.contact = input("Contact");
            branchController.update(dto);
        }, this::loadBranches);
    }//GEN-LAST:event_branchBtnUpdateActionPerformed

    private void branchBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchBtnAddActionPerformed
        runAction(() -> {
            BranchDTO dto = new BranchDTO();
            dto.branchCode = input("Branch Code");
            dto.name = input("Name");
            dto.address = input("Address");
            dto.contact = input("Contact");
            branchController.create(dto);
        }, this::loadBranches);
    }//GEN-LAST:event_branchBtnAddActionPerformed

    private void configureRoleAccess() {
        if (isAdmin()) {
            return;
        }

        removeTab("Branches");
        removeTab("Categories");
    }

    private void removeTab(String title) {
        for (int i = jTabbedPane4.getTabCount() - 1; i >= 0; i--) {
            if (title.equals(jTabbedPane4.getTitleAt(i))) {
                jTabbedPane4.removeTabAt(i);
            }
        }
    }

    private void initializeData() {
        loadBranches();
        loadCategories();
        loadEquipment();
        loadCustomers();
        loadMemberships();
        loadReservations();
        loadRentals();
    }

    private void loadBranches() {
        DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
        model.setRowCount(0);
        for (BranchDTO row : branchController.list()) {
            model.addRow(new Object[]{row.branchId, row.branchCode, row.name, row.contact});
        }
    }

    private void loadCategories() {
        DefaultTableModel model = (DefaultTableModel) jTable6.getModel();
        model.setRowCount(0);
        for (CategoryDTO row : categoryController.list()) {
            model.addRow(new Object[]{
                row.categoryId,
                row.name,
                row.priceFactor,
                row.weekendMultiplier,
                row.lateFeePerDay,
                row.active
            });
        }
    }

    private void loadEquipment() {
        loadEquipment(equipmentController.list(scopeBranch()));
    }

    private void loadEquipment(java.util.List<EquipmentDTO> rows) {
        DefaultTableModel model = (DefaultTableModel) jTable7.getModel();
        model.setRowCount(0);
        for (EquipmentDTO row : rows) {
            model.addRow(new Object[]{
                row.equipmentId,
                row.branchId,
                row.categoryId,
                row.brand,
                row.model,
                row.status
            });
        }
    }

    private void loadCustomers() {
        DefaultTableModel model = (DefaultTableModel) jTable8.getModel();
        model.setRowCount(0);
        for (CustomerDTO row : customerController.list()) {
            model.addRow(new Object[]{row.customerId, row.name, row.nicPassport, row.membershipId});
        }
    }

    private void loadMemberships() {
        DefaultTableModel model = (DefaultTableModel) jTable9.getModel();
        model.setRowCount(0);
        for (MembershipDTO row : membershipController.list()) {
            model.addRow(new Object[]{row.membershipId, row.levelName, row.discountPercentage});
        }
    }

    private void loadReservations() {
        DefaultTableModel model = (DefaultTableModel) jTable10.getModel();
        model.setRowCount(0);
        for (ReservationDTO row : reservationController.list(scopeBranch())) {
            model.addRow(new Object[]{
                row.reservationId,
                row.equipmentId,
                row.customerId,
                row.startDate,
                row.endDate,
                row.status
            });
        }
    }

    private void loadRentals() {
        loadRentals(rentalController.list(scopeBranch()));
    }

    private void loadRentals(java.util.List<RentalDTO> rows) {
        DefaultTableModel model = (DefaultTableModel) jTable11.getModel();
        model.setRowCount(0);
        for (RentalDTO row : rows) {
            model.addRow(new Object[]{
                row.rentalId,
                row.equipmentId,
                row.customerId,
                row.startDate + " to " + row.endDate,
                row.finalAmount,
                row.lateFee,
                row.damageCharge,
                row.settlementAmount,
                row.rentalStatus
            });
        }
    }

    private boolean isAdmin() {
        return user == null || "Admin".equalsIgnoreCase(user.role);
    }

    private Integer scopeBranch() {
        return isAdmin() ? null : user.branchId;
    }

    private int inputBranch() {
        if (isAdmin()) {
            return intInput("Branch ID");
        }
        return user.branchId;
    }

    private String input(String label) {
        String value = JOptionPane.showInputDialog(this, label);
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException(label + " is required.");
        }
        return value.trim();
    }

    private String nullableInput(String label) {
        String value = JOptionPane.showInputDialog(this, label);
        return (value == null || value.isBlank()) ? null : value.trim();
    }

    private int intInput(String label) {
        try {
            return Integer.parseInt(input(label));
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException("Invalid integer value for " + label + ".");
        }
    }

    private Integer nullableIntInput(String label) {
        String value = nullableInput(label);
        return value == null ? null : Integer.valueOf(value);
    }

    private BigDecimal decimalInput(String label) {
        try {
            return new BigDecimal(input(label));
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException("Invalid decimal value for " + label + ".");
        }
    }

    private LocalDate dateInput(String label) {
        try {
            return LocalDate.parse(input(label));
        } catch (DateTimeParseException ex) {
            throw new IllegalArgumentException("Invalid date format for " + label + ". Use YYYY-MM-DD.");
        }
    }

    private boolean boolInput(String label) {
        return Boolean.parseBoolean(input(label));
    }

    @FunctionalInterface
    private interface ActionTask {
        void run() throws Exception;
    }

    private void runAction(ActionTask action, Runnable refresh) {
        try {
            action.run();
            if (refresh != null) {
                refresh.run();
            }
            JOptionPane.showMessageDialog(this, "Success.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainUi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton branchBtnAdd3;
    private javax.swing.JButton branchBtnDlt3;
    private javax.swing.JButton branchBtnRefresh3;
    private javax.swing.JButton branchBtnUpdate3;
    private javax.swing.JButton ctgBtnActive;
    private javax.swing.JButton ctgBtnAdd;
    private javax.swing.JButton ctgBtnRefresh;
    private javax.swing.JButton ctgBtnUpdate;
    private javax.swing.JButton ctmBtnAdd;
    private javax.swing.JButton ctmBtnRefresh;
    private javax.swing.JButton ctmBtnUpdate;
    private javax.swing.JButton eqpBtnAdd;
    private javax.swing.JButton eqpBtnRefresh;
    private javax.swing.JButton eqpBtnSearch;
    private javax.swing.JButton eqpBtnUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable12;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JButton mbshipBtnRefresh;
    private javax.swing.JButton rentalBtnCreate;
    private javax.swing.JButton rentalBtnOverdue;
    private javax.swing.JButton rentalBtnRefresh;
    private javax.swing.JButton rentalBtnReturn;
    private javax.swing.JButton reportBtnEqpUtil;
    private javax.swing.JButton reportBtnRevenue;
    private javax.swing.JButton revervBtnCancel;
    private javax.swing.JButton revervBtnConvertToRental;
    private javax.swing.JButton revervBtnCreate;
    private javax.swing.JButton revervBtnRefresh;
    // End of variables declaration//GEN-END:variables

    
}
